### ISSUE TITLE
Polluted browser for other UAA

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa-singular#8] opened 2018-06-20 08:35 UTC
I'm not sure what I'm seeing. Let me explain.

I played with the example uaa-singular app earlier today.

Later, with the same browser, I went to login to https://console.run.pivotal.io via https://login.run.pivotal.io and when finished it redirected to: https://console.run.pivotal.io/singular/postauth.html#token_type=bearer&id_token=xxxx

What might have happened here?

/cc @sreetummidi

**Comment by swalchemist** [comment] 2024-03-12 20:45
I'm getting a 404 on https://console.run.pivotal.io/ now, so I can't reproduce. Closing.

**Closed by swalchemist** 2024-03-12 20:45 UTC
